rsvp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'create_rsvp/$', views.create_rsvp, name='create_rsvp'),
]

wedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gifts/', include('gifts.urls', namespace='gifts')),
    url(r'^rsvp/', include('rsvp.urls', namespace='rsvp')),
    url(r'^', include('wedding_app.urls', namespace='wedding')),
]

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)

wedding_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.user_login, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^party/$', views.party, name='party'),
]

wedding_app/models.py
from datetime import datetime

from django.db import models
from django import forms

class SingletonModel(models.Model):

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

class Slider(models.Model):
    pass

class SliderImage(SingletonModel):
    slider = models.ForeignKey(Slider, on_delete=models.CASCADE)
    image = models.ImageField()
    text = models.CharField(max_length=200)

class Couple(SingletonModel):
    bride_name = models.CharField(verbose_name='imię_panny',
                                  max_length=100,
                                  default='Bride')
    bride_last_name = models.CharField(verbose_name='nazwisko_panny',
                                       max_length=100,
                                       default='Smith')
    groom_name = models.CharField(verbose_name='imię_kawalera',
                                  max_length=100,
                                  default='Groom')
    groom_last_name = models.CharField(verbose_name='nazwisko_kawalera',
                                       max_length=100,
                                       default='Smith')

    class Meta:
        verbose_name = 'para młoda'
        verbose_name_plural = 'para młoda'

    def __str__(self):
        return 'Para młoda'

class Wedding(SingletonModel):
    when = models.DateTimeField(verbose_name='kiedy',
                                default=datetime.now())
    where = models.CharField(verbose_name='kościół',
                             max_length=200,
                             default='Wedding place')
    image = models.ImageField(verbose_name='obrazek',
                              blank=True)
    description = models.CharField(verbose_name='opis',
                                   max_length=1000,
                                   default='Wedding description')
    address = models.CharField(verbose_name='adres',
                               max_length=200,
                               default='plac Defilad, Warszawa')

    class Meta:
        verbose_name = 'ślub'
        verbose_name_plural = 'ślub'

    def __str__(self):
        return 'Ślub'

class Party(SingletonModel):
    when = models.DateTimeField(verbose_name='kiedy',
                                default=datetime.now())
    where = models.CharField(verbose_name='sala',
                             max_length=200,
                             default='Party place')
    image = models.ImageField(verbose_name='obrazek',
                              blank=True)
    description = models.CharField(verbose_name='opis',
                                   max_length=1000,
                                   default='Party description')
    address = models.CharField(verbose_name='adres',
                               max_length=200,
                               default='plac Defilad, Warszawa')

    class Meta:
        verbose_name = 'wesele'
        verbose_name_plural = 'wesele'

    def __str__(self):
        return 'Wesele'

class Configuration(SingletonModel):
    login_required = models.BooleanField(verbose_name='logowanie',
                                         default=True)

    class Meta:
        verbose_name = "konfiguracja"
        verbose_name_plural = "konfiguracja"

    def __str__(self):
        return 'Konfiguracja'

wedding_app/views.py
import datetime
import locale
import pytz

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from json import dumps as json_dumps

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from .models import Wedding, Party, Couple, Configuration
from rsvp.forms import RSVPform
from rsvp.rsvp import get_rsvp_form

def date_handler(obj):
    if hasattr(obj, 'isoformat'):
        return obj.isoformat()
    else:
        raise TypeError

@login_required
def home(request):
    if settings.STAGE == 'development':
        locale.setlocale(locale.LC_ALL, 'pl_PL.utf8')
    else:
        locale.setlocale(locale.LC_ALL, 'pl_PL.UTF-8')

    #Get information about wedding
    wedding = Wedding.load()
    wedding.when = timezone.localtime(wedding.when)
    wedding_day = wedding.when.strftime('%A').title()
    wedding_time_json = json_dumps({'wedding_time': wedding.when}, default=date_handler)
    print(wedding.when)

    #Get information about party
    party = Party.load()
    party.when = timezone.localtime(party.when)

    #Get information about couple
    couple = Couple.load()

    #Get RSVP informations
    rsvp_form = get_rsvp_form(request.session)
    rsvp_success = request.session.get('rsvp_success', False)

    context = {
        'wedding': wedding,
        'party': party,
        'couple': couple,
        'wedding_day': wedding_day,
        'wedding_time_json': wedding_time_json,
        'rsvp_form': rsvp_form,
        'rsvp_success': rsvp_success,
    }

    return render(request,
                  'wedding_app/pages/home.html',
                  context)

@login_required
def party(request):
    if settings.STAGE == 'development':
        locale.setlocale(locale.LC_ALL, 'pl_PL.utf8')
    else:
        locale.setlocale(locale.LC_ALL, 'pl_PL.UTF-8')

    #Get information about wedding
    wedding = Wedding.load()
    wedding.when = timezone.localtime(wedding.when)
    wedding_day = wedding.when.strftime('%A').title()

    #Get information about party
    party = Party.load()
    party.when = timezone.localtime(party.when)

    #Get information about couple
    couple = Couple.load()

    context = {
        'wedding': wedding,
        'party': party,
        'couple': couple,
        'wedding_day': wedding_day,
    }

    return render(request,
                  'wedding_app/pages/party.html',
                  context)

def user_login(request):
    username = 'user'

    if request.method == 'POST':
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('wedding:home'))
    else:
        config = Configuration.load()

        if config.login_required:
            form = AuthenticationForm()

            #Get information about couple
            couple = Couple.load()

            context = {
                'form': form,
                'couple': couple,
            }
            return render(request,
                   'wedding_app/pages/login.html',
                   context)
        else:
            if request.user.is_authenticated():
                user = request.user
            else:
                user = User.objects.get(username=username)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            if user is not None:
                login(request, user)
                return redirect(reverse('wedding:home'))

wedding_app/templates/wedding_app/base.html
<!DOCTYPE html>
<html lang="pl">

{% load staticfiles %}
{% load compress %}

    {% block head %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="wedding">
        <meta name="author" content="www.gajownik.com">

        <title>{{ couple.bride_name }} & {{ couple.groom_name }}</title>

        <!-- Custom Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Great+Vibes&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

        <!-- Compress -->
        {% compress css %}
            <!-- Bootstrap Core CSS -->
            <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

            <!-- Custom Fonts -->
            <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

            <!-- Plugin CSS -->
            <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
            <link href="{% static 'vendor/bootstrap-switch/css/bootstrap3/bootstrap-switch.css' %}" rel="stylesheet">

            <!-- Theme LESS -->
            <link rel="stylesheet" type="text/less" href="{% static 'less/creative.less' %}">
            <link rel="stylesheet" type="text/less" href="{% static 'less/wedding.less' %}">
        {% endcompress %}

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    {% endblock %}

    <body>
        {% block menu %}
            <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span>{{ couple.bride_name }}</span>
                            <img class="svg" src="{% static 'img/menu_image.svg' %}" width="50px" height="50px">
                            <span>{{ couple.groom_name }}</span>
                        </button>
                        <!--<a class="navbar-brand page-scroll" href="{% url 'wedding:home' %}">{{ couple.bride_name }} & {{ couple.groom_name }}</a>-->
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav flex-list">
                            <li>
                                <a href="{% url 'wedding:home' %}">Strona główna</a>
                            </li>
                            <li>
                                <a href="{% url 'wedding:party' %}">Szczegóły uroczystości</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        {% endblock %}

    {% block content %}{% endblock %}

    {% block footer %}
        <div class="bg-secondary row footer text-center">
            <h4>Made by <a href="http://www.gajownik.com">gajownik.com</a></h4>
            <h6>Icons designed by Freepik and distributed by <a href="http://www.flaticon.com">Flaticon</a></h6>
            <h6>Maps Icons Collection <a href="http://www.mapicons.mapsmarker.com">mapicons.mapsmarker.com</a></h6>
        </div>
    {% endblock %}

    <!-- JS files -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    {% compress js %}
        <!-- jQuery -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

        <!-- Plugin JavaScript -->
        <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
        <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

        <!-- Theme JavaScript -->
        <script src="{% static 'js/creative.min.js' %}"></script>
        <script src="{% static 'js/svgcolor.js' %}"></script>
    {% endcompress %}
</body>

</html>