rsvp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'create_rsvp/$', views.create_rsvp, name='create_rsvp'),
]

wedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gifts/', include('gifts.urls', namespace='gifts')),
    url(r'^rsvp/', include('rsvp.urls', namespace='rsvp')),
    url(r'^', include('wedding_app.urls', namespace='wedding')),
]

#urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)

rsvp/models.py
from django.db import models

class RSVP(models.Model):
    name = models.CharField(verbose_name="imię",
                            max_length=100,
                            blank=False,
                            null=False)
    last_name = models.CharField(verbose_name="nazwisko",
                                 max_length=100,
                                 blank=False,
                                null=False)
    adults_number = models.PositiveIntegerField(verbose_name="dorośli",

                                                blank=False,
                                                null=False)
    childrens_number = models.PositiveIntegerField(verbose_name="dzieci",
                                                   blank=False,
                                                   null=False)
    transport = models.BooleanField(verbose_name="transport",
                                    default=False)
    accomodation = models.BooleanField(verbose_name="nocleg",
                                       default=False)

    class Meta:
        verbose_name = 'potwierdzenie'
        verbose_name_plural = 'potwierdzenia'

    def __str__(self):
        return self.name + ' ' + self.last_name

rsvp/forms.py
from django import forms
from .models import RSVP

class RSVPform(forms.ModelForm):
    class Meta:
        model = RSVP
        fields = '__all__'
        localized_fields = '__all__'
        widgets = {
            'adults_number': forms.NumberInput(attrs={
                'min': '1', 'max': '10', 'step': '1', 'placeholder': '> 18 lat', 'class': 'form-control',
            }),
            'childrens_number': forms.NumberInput(attrs={
                'min': '0', 'max': '10', 'step': '1', 'placeholder': '< 18 lat', 'class': 'form-control'
            }),
            'name': forms.TextInput(attrs={'placeholder': 'Imię', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Nazwisko', 'class': 'form-control'}),
            'transport': forms.CheckboxInput(),
            'accomodation': forms.CheckboxInput(),
        }

rsvp/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse

from .models import RSVP
from .forms import RSVPform

def create_rsvp(request):
    if request.method == 'POST':
        data = {
            'name': request.POST.get('name'),
            'last_name': request.POST.get('last_name'),
            'adults_number': request.POST.get('adults_number'),
            'childrens_number': request.POST.get('childrens_number'),
            'transport': request.POST.get('transport') == 'true',
            'accomodation': request.POST.get('accomodation') == 'true',
        }

        rsvp_form = RSVPform(data)

        if rsvp_form.is_valid():
            rsvp_form.save()
            request.session['rsvp_success'] = True

            return JsonResponse(
                data={},
                status=200
            )
        else:
            errors = rsvp_form.errors.as_json()

            return JsonResponse(
                data={'errors': errors},
                status=400
            )

rsvp/templates/rsvp/rsvp.html
{% block rsvp %}
{% load staticfiles %}

    <link href="{% static 'vendor/bootstrap-switch/bootstrap3/bootstrap-switch.css' %}" rel="stylesheet">

    <div class="container">
        <div class="panel panel-primary dialog-panel">
            <div class="panel-heading text-center">
                <h3>Będziesz z nami?</h3>
            </div>
            <div class="panel-body">
                {% if not rsvp_success %}
                <form id="rsvp-form" class="form-horizontal" role="form" action="{% url 'rsvp:create_rsvp' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-2 col-md-offset-2" for="{{ rsvp_form.name.id_for_label }}">
                            Imię i nazwisko
                        </label>
                        <div class="col-md-8">
                            <div class="col-md-4">
                                <div class="form-group internal {% if rsvp_form.name.errors %} form-error {% endif %}">
                                    {{ rsvp_form.name }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group internal {% if rsvp_form.last_name.errors %} form-error {% endif %}">
                                    {{ rsvp_form.last_name }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2 col-md-offset-2" for="{{ rsvp_form.adults_number.id_for_label }}">
                            Goście
                        </label>
                        <div class="col-md-8">
                            <div class="col-md-4">
                                <div class="form-group internal {% if rsvp_form.adults_number.errors %} form-error {% endif %}">
                                    {{ rsvp_form.adults_number }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group internal {% if rsvp_form.childrens_number.errors %} form-error {% endif %}">
                                    {{ rsvp_form.childrens_number }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 flex">
                            <label class="flex-cell flex-center" for='{{ rsvp_form.transport.id_for_label }}'>
                                Transport
                            </label>
                            <div class="flex-cell flex-center">
                                {{ rsvp_form.transport.errors }}
                                {{ rsvp_form.transport }}
                            </div>
                            <label class="flex-cell flex-center" for=" {{ rsvp_form.accomodation.id_for_label }}">
                                Nocleg
                            </label>
                            <div class="flex-cell flex-center">
                                {{ rsvp_form.accomodation.errors }}
                                {{ rsvp_form.accomodation }}
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 flex">
                        <input class="button flex-centered" type="submit" value="Potwierdź">
                    </div>
                </form>
                {% else %}
                    <h4 class="text-center">Dziękujemy za potwierdzenie swojej obecności. Do zobaczenia!</h4>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}